### ISSUE TITLE
1.0.3 is taking a lot of time after update 

### ISSUE THREAD

**Issue by davidiesel** [L1ghtmann/IAmSpeed#2]
1.0.3 is taking a lot of time after update was working great before update

**Comment by UsrLightmann** [comment]
@davidiesel, I've sent you another build in our old email thread. 

If you get a chance, I'd love to know if you fare any better with it. No rush. 

Thanks in advance!

**Comment by UsrLightmann** [comment]
I've attempted to fix this issue in v1.0.4 which should be live in the next 12 hrs. If you could give it a go once it's been released and let me know if your issue has indeed been resolved, that would be super helpful. Thanks in advance!

**Comment by davidiesel** [comment]
Sure brother i wil

David Oliveira 
JMJ


On 06-Jan-2022, at 08:54, Lightmann ***@***.***> wrote:

﻿

I've attempted to fix this issue in v1.0.4 which should be live in the next 12 hrs. If you could give it a go once it's been released and let me know if your issue has indeed been resolved, that would be super helpful. Thanks in advance!

**Comment by UsrLightmann** [comment]
Any luck this time around?

**Comment by L1ghtmann** [comment]
Fixed in v1.0.7.
